apiVersion: apps/v1
kind: Deployment
metadata:
  name: jw-rtp
  namespace: jw
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  jw-rtp
  template:
    metadata:
      labels:
        app:  jw-rtp
    spec:
      imagePullSecrets:
      - name: jfrogcred
      containers:
      - name:  jw-rtp                                               # Name of container
        image: joweyel01.jfrog.io/jweyel-docker-local/ttrend:2.1.2  # Image of used container
        imagePullPolicy: Always
        ports:
        - containerPort: 8000  # accessible on port 8000
        env:
        - name: CONSUMER_KEY
          value: "G6lmKhsi0V9TvXt6oKTfjRBCr"
        - name: CONSUMER_SECRET
          value: "bEyDk8X0p8SQd4376eoNV4nH8To22sHcJOoFt0ZqOKS37hhI4q"
        - name: ACCESS_TOKEN
          value: "9703354-52rXHD6EeOQeYyhtNz1w8UVOgbcLcgOo4O7MB6WV3"
        - name: ACCESS_TOKEN_SECRET
          value: "zBThlZDEp8qnu7NwwdHNth8eg3Rf9zqbvUEFUTaZtN2SF"