apiVersion: v1
kind: Service
metadata:
  name:  jw-rtp-service
  namespace: jw
spec:
  type: NodePort
  selector:
    app: jw-rtp
  ports:
  - nodePort: 30082  # port that allows access to node
    port: 8000
    targetPort: 8000